##
## EPITECH PROJECT, 2020
## CPE_dante_2019 [SSH: 192.168.159.130]
## File description:
## Makefile
##

OBJS	=	./main.o

CFLAGS	=	-I ./include
CFLAGS	+=	-Wall -Wextra
CFLAGS	+=	-g3

$(OBJS): ./include/settings.h
